meta_product_name: "Ztrut"
meta_title: "Ztrut - Former un groupe grâce à vos voisins"
meta_description: "Application pour rencontrer, trouver des musiciens pour jouer de la musique"
meta_image: "logo_index.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
